"""Final Schema with Districts

Revision ID: df3c8d901de9
Revises: 
Create Date: 2025-12-08 19:44:48.673240

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'df3c8d901de9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('pib_total', sa.Float(), nullable=True),
    sa.Column('pib_per_capita', sa.Float(), nullable=True),
    sa.Column('total_companies', sa.Integer(), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_cities_geom', 'cities', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_cities_code'), 'cities', ['code'], unique=True)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_table('city_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_catalog_code'), 'city_catalog', ['code'], unique=True)
    op.create_index(op.f('ix_city_catalog_id'), 'city_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_city_catalog_name'), 'city_catalog', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=True)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_city_catalog_name'), table_name='city_catalog')
    op.drop_index(op.f('ix_city_catalog_id'), table_name='city_catalog')
    op.drop_index(op.f('ix_city_catalog_code'), table_name='city_catalog')
    op.drop_table('city_catalog')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_code'), table_name='cities')
    op.drop_index('idx_cities_geom', table_name='cities', postgresql_using='gist')
    op.drop_table('cities')
    # ### end Alembic commands ###