"""Add reference years to city

Revision ID: f5424ef3ac32
Revises: df3c8d901de9
Create Date: 2025-12-08 20:29:48.648539

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f5424ef3ac32'
down_revision = 'df3c8d901de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('pib_year', sa.Integer(), nullable=True))
    op.add_column('cities', sa.Column('companies_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'companies_year')
    op.drop_column('cities', 'pib_year')
    # ### end Alembic commands ###